### ISSUE TITLE
No `base36` and why your `base64` is different from `Convert.ToBase64String()` ?

### ISSUE THREAD

**Issue by John0King** [pnowosie/ByteEncodings#1]

**Comment by pnowosie** [comment]
Hey @John0King 
Thanks for the question, I'm glad to address it.

Regarding `base36` - is missed probably because it didn't appear to me as a standard. By standard I mean something which decides if digits comes first in alphabet and whether should letters be uppercased.
Hence it should quite easy to create `base36`-ish encoding, e.g:
```c#
Alphabet Base36Alphabet  = new Alphabet(KnownAlphabets.DigitsAndLetters);
```

Considering `base64` (and `base16` HEX as well) encoding you should always prefer to use `Convert.ToBase64String()`. Reason for that is alphabets of power-of-2 length can be more efficiently encoded than doing module-divide approach. 
I thought about taking different approach for such power-of-2 encodings :bulb:  - but concluded to keep it simple. Definitely I need to highlight these differences more in readme and unit tests.

**Comment by John0King** [comment]
Thank for your reply ,  `base36` is indeed not  a RFC standard, but I found a [wiki](https://en.wikipedia.org/wiki/Base36)  and there is a vb.net implementation  so no worries.
about `base64` , It's better to also make a note on code commits .
